### ISSUE TITLE
Add a ROADMAP.md

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#227]
It would be nice to add a roadmap letting folks know our priorities for the Blender exporter, and what sort of PRs would be accepted. A few that come to mind:

- [ ] Support Blender 2.8 (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/87)
  - [Milestone](https://github.com/KhronosGroup/glTF-Blender-Exporter/milestone/3)
- [ ] Principled BSDF (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/101)
- [ ] KHR_texture_transform (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/226)
- [ ] UV layouts (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/194)
- General bug fixes

**Comment by emackey** [comment]
Let's use this issue as a roadmap issue, rather than creating a ROADMAP.md file, and convert the bullets above to checkboxes.

For what it's worth, on Cesium we have a category of issue called "Roadmap" and we track the progress of large, multi-PR projects in the roadmap issue rather than in a file.

**Comment by donmccurdy** [comment]
What is the significance of the "Roadmap" label being added to an issue? Does that just signify it's an issue that (1) is wanted by project maintainers, and (2) will require multiple PRs? I'm thinking less of tracking multi-PR issues here, and more of giving users a single place to find our goals and ways to contribute.

But using an issue instead of an MD file is fine with me.
